#!/bin/bash

set -o errexit

dir=$(dirname "$0")
root="$dir/../.."
# shellcheck source=./__helping-functions.sh
source "$dir/../__helping-functions.sh"

BUILD_DIR="$root/docs/db/build"
RESULT_FOLDER="$root/docs/docs/backend/database"
META_DATA_FILE="$root/docs/db/database_metadata.json"

# Set node module path to global modules
export NODE_PATH=$(npm root -g)
# prepare processing folder
mkdir -p "$BUILD_DIR"

# Generate a SQL dump file which allows extraction of the important schema information
# Tables, Columns, Primary Key, foreign keys
#https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html
SQL_DUMP_FILE="$BUILD_DIR/schema_sql_dump.sql"

mysqldump -h "db" -u "root" -p"root" --skip-comments --no-data --skip-add-drop-table foodsharing > $SQL_DUMP_FILE

# Extract modules and table usage from code base
TABLE_USAGE_FILE="$BUILD_DIR/extract_tables_usage_from_php.grep_result"
MODULE_FILE="$BUILD_DIR/modules.json"
grep --include=\*.php -E "([^\$]fs_[a-zA-Z0-9_]+)" -R -B5 -A 2 -n "$root/src" > $TABLE_USAGE_FILE
node "$dir/generate-db-documenation/extract_tables_usage_from_php_parser.js"  $BUILD_DIR $TABLE_USAGE_FILE $MODULE_FILE

# Transform SQL dump and usage information to documentation
node "$dir/generate-db-documenation/sql_to_documentation.js" $BUILD_DIR $RESULT_FOLDER $SQL_DUMP_FILE $META_DATA_FILE $MODULE_FILE

echo
echo "GENERATION COMPLETE"
