#!/bin/bash

set -o errexit

dir=$(dirname "$0")

# shellcheck source=./inc.sh
source "$dir/inc.sh"

# Generate a SQL dump file which allows extraction of the important schema information
# Tables, Columns, Primary Key, foreign keys
#https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html
exec-in-container mdbook bash "/app/scripts/generate-db-documenation/mysql_generate_documentation"
