#!/bin/bash

export FS_ENV=test

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

echo $SECONDS seconds elapsed

log-header "Preparing execution environment: Prepare PHP config & application"
bin/console foodsharing:setup
# configure path to application
# *https://forums.docker.com/t/sed-couldnt-open-temporary-file-xyz-permission-denied-when-using-virtiofs/125473/2
tmpfile=$(mktemp tmp_file_XXXXXX)
sed "s#/app#$CI_PROJECT_DIR#g" /usr/local/etc/php-fpm.d/fpm.conf > $tmpfile; cat $tmpfile > /usr/local/etc/php-fpm.d/fpm.conf; rm $tmpfile
# let PHP-FPM run as root
# sed -i "s#www-data#root#g" /usr/local/etc/php-fpm.d/fpm.conf
# disable xdebug
# rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

php-fpm -R 2> php_fpm_err.log &

log-header "Initializing database"
SECONDS=0
mysql -u root -proot -hdb --execute="drop database if exists foodsharing; create database foodsharing"
php run.php Mails queueWorker &
vendor/bin/phinx migrate
echo $SECONDS seconds elapsed

log-header "Waiting for assets to be generated ..."
while ! [ "$(ls -A assets)" ];
do
sleep 1;
echo -ne ".";
done
echo

log-header "Running tests"
failed=0
SECONDS=0

vendor/bin/codecept run -s acceptance --xml=report-code.xml --html=report-code.html --coverage-text --coverage-cobertura="code-cobertura.xml" || failed=1
echo $SECONDS seconds elapsed

if [ $failed -eq 0 ] # first run succeeded, we can finish early
then
    exit 0
else
    exit 1
fi
