#!/usr/bin/env bash
# This script is creating the artifacts for deployment

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

gitlab_start_section composer Composer
composer install --verbose --prefer-dist --no-progress --no-interaction --no-dev --classmap-authoritative --no-scripts --ignore-platform-reqs
composer dump-autoload --classmap-authoritative
gitlab_end_section composer

log-header "Create folder structure ..."
bin/console foodsharing:setup

log-header "Installing assets ..."
bin/console assets:install
