#!/bin/bash

export CURRENT_USER=$(id -u):$(id -g)

set -o errexit

dir=$(dirname "$0")

base_dir=$(cd "$dir/.." && pwd)

# shellcheck source=./__helping-functions.sh
source "$dir"/__helping-functions.sh

# Remove docker dev containers
FS_ENV=dev
"$dir"/containers-remove
# Remove docker test containers
FS_ENV="test"
"$dir"/containers-remove

log-header "Removing local node_modules"
find $base_dir -name "node_modules" -type d -prune | xargs du -chs # prints the folders
find $base_dir -name "node_modules" -type d -prune -exec rm -rf '{}' + # removes the folders

log-header "Removing directories"
rm -vrf \
  "$base_dir"/assets \
  "$base_dir"/images \
  "$base_dir"/data \
  "$base_dir"/cache \
  "$base_dir"/var \
  "$base_dir"/tmp \
  "$base_dir"/tests/_output

log-header "All clean!"
