#!/bin/bash

export FS_ENV=dev
export CURRENT_USER=$(id -u):$(id -g)

set -o errexit

dir=$(dirname "$0")

base_dir=$(cd "$dir/.." && pwd)

# shellcheck source=./inc.sh
source "$dir"/inc.sh

echo "---------------------"
echo ">>> Removing local node_modules"
(cd "$dir" && rm -rf node_modules)

echo "---------------------"
echo ">>> Removing containers"
"$dir"/rm
FS_ENV="test" "$dir"/rm

echo "---------------------"
echo ">>> Removing directories"

rm -rf \
  "$base_dir"/assets \
  "$base_dir"/images \
  "$base_dir"/data \
  "$base_dir"/cache \
  "$base_dir"/var \
  "$base_dir"/tmp

echo "All clean!"
