#!/bin/bash

export FS_ENV=dev
export CURRENT_USER=$(id -u):$(id -g)

if [ $@ ]; then
  FS_ENV=$@
fi

# set -o errexit tells the shell to exit as soon as a command exits with non-zero status, i.e. fails
set -o errexit

dir=$(dirname "$0")

# source runs the content of the argument as if it was here (without launching a subshell!)
# __helping-functions.sh defines basic functions, mainly to run commands in containers
# shellcheck source=./__helping-functions.sh
source "$dir"/__helping-functions.sh

log-header "Stopping $FS_ENV containers ..."
dc stop
