#!/bin/bash
dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

if [ "$1" ]; then
  FS_ENV="$1"
fi

log-header "Clear assets ..."
rm -rf "$(cd "$dir/.." && pwd)"/assets/*

log-header "Check for new images ..."
"$dir"/docker-compose build --pull

log-header "Bringing up containers ..."
"$dir"/docker-compose up -d

log-header "Waiting for assets to be generated ..."
wait-for-assets
exec-in-container app bin/console assets:install

"$dir"/__helping-print-intro.sh
