#!/bin/bash

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

if [ "$1" ]; then
  FS_ENV="$1"
fi

log-header "Stopping $FS_ENV containers ..."
"$dir"/docker-compose stop
