#!/bin/bash
dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

if [ "$1" ]; then
  FS_ENV="$1"
fi

# set -o errexit tells the shell to exit as soon as a command exits with non-zero status, i.e. fails
set -o errexit

log-header "Clear assets ..."
rm -rf "$(cd "$dir/.." && pwd)"/assets/*

log-header "Restarting $FS_ENV containers ..."
"$dir"/docker-compose restart

log-header "Waiting for assets to be generated ..."
wait-for-assets
exec-in-container app bin/console assets:install

"$dir"/__helping-print-intro.sh
