#!/bin/bash

set -o errexit

dir=$(dirname "$0")

# shellcheck source=./__helping-functions.sh
source "$dir"/__helping-functions.sh

name="foodsharing_$FS_ENV"

log-header "Kill $FS_ENV containers"
dc kill

log-header "Removing $FS_ENV containers"
containers=$(docker ps -aq -f name="$name")
if [ "x" != "x$containers" ]; then
  echo "$containers" | xargs docker rm
else
  echo "no container to remove"
fi

log-header "Removing $FS_ENV Volumes"
volumes=$(docker volume ls -q -f name="$name")
if [ "x" != "x$volumes" ]; then
  remove=""
  for V in $volumes; do
    if [[ $V != *"_cache" ]]; then
      remove="$V $remove"
    fi
  done
  echo "Removing volumes: $remove"
  echo "$remove" | xargs docker volume rm
else
  echo "no volumes to remove"
fi
