#!/bin/bash

set -o errexit

dir=$(dirname "$0")

# shellcheck source=./__helping-functions.sh
source "$dir/__helping-functions.sh"

# Generate a SQL dump file which allows extraction of the important schema information
# Tables, Columns, Primary Key, foreign keys
#https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html
exec-in-container docs bash "/app/scripts/generate-documentation/mysql_generate_documentation"
