#!/usr/bin/env bash

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

# Generate a SQL dump file which allows extraction of the important schema information
# Tables, Columns, Primary Key, foreign keys
#https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html
exec-in-container docs bash "/app/scripts/generate-documentation/mysql_generate_documentation"
