#!/bin/bash

# exit shell as soon as a command fails (exit status not 0):
set -o errexit
# Treat unset variables as an error when substituting:
set -o nounset

if [[ "$CI_ENVIRONMENT_NAME" == "production" ]]
then
  ssh deploy@foodsharing.network sudo systemctl restart fs-websocket.service
  ssh deploy@foodsharing.network sudo systemctl restart fs-mailqueuerunner.service
fi
