#!/bin/bash
# run docker-compose with the container specified by $FS_ENV and a suitable project name
# which command to run by docker-compose and additional arguments is specified by the arguments
# of this script

# Export the current host operating system to FS_PLATFORM
unameOut="$(uname -s)"
case "${unameOut}" in
    Darwin*)    export FS_PLATFORM=mac;;
    *)          export FS_PLATFORM=default;;
esac

# check if gp is there
if [[ $(type -t gp) == file ]];
then
    FS_PLATFORM=gitpod
fi

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

docker-compose \
  --file "$dir"/../docker/docker-compose.yml \
  --file "$dir"/../docker/docker-compose."$FS_ENV".yml \
  --project-name foodsharing_"$FS_ENV" \
  "$@"
