#!/bin/bash

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

log-header "Fixing php code"
run-in-container app vendor/bin/php-cs-fixer fix

log-header "Fixing js client code"
run-in-container client yarn lint --fix

log-header "Fixing js websocket code"
run-in-container websocket yarn lint --fix
