#!/bin/bash

export FS_ENV=dev
export CURRENT_USER=$(id -u):$(id -g)

set -o errexit

dir=$(dirname "$0")

# shellcheck source=./__helping-functions.sh
source "$dir"/__helping-functions.sh

log-header "Fixing js client code"
run-in-container client yarn lint --fix

log-header "Fixing js chat code"
run-in-container chat yarn lint --fix
