#!/bin/bash

export FS_ENV=dev
export CURRENT_USER=$(id -u):$(id -g)

set -o errexit

dir=$(dirname "$0")

# shellcheck source=./__helping-functions.sh
source "$dir"/__helping-functions.sh

log-header "Fixing php code"
run-in-container app vendor/bin/php-cs-fixer fix
