#!/bin/bash

export FS_ENV=dev
export CURRENT_USER=$(id -u):$(id -g)

set -o errexit

dir=$(dirname "$0")

# shellcheck source=./__helping-functions.sh
source "$dir"/__helping-functions.sh

echo "Linting php with php-cs-fixer"
run-in-container app vendor/bin/php-cs-fixer fix --dry-run --diff --verbose

echo "Linting php with parallel-lint"
run-in-container app vendor/bin/parallel-lint --exclude vendor .

echo "Linting php with phpstan"
run-in-container app vendor/bin/phpstan analyse --memory-limit=768M
