#!/bin/bash

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

echo "Linting client js"
run-in-container client yarn lint

echo "Linting websocket js"
run-in-container websocket yarn lint
