#!/bin/bash
# create necessary directories in container app (the main php app container)

# use dev if not specified yet
export FS_ENV=${FS_ENV:-dev}
export CURRENT_USER=${CURRENT_USER:-$(id -u):$(id -g)}

set -o errexit

dir=$(dirname "$0")

# shellcheck source=./inc.sh
source "$dir"/inc.sh

# directories used by the application

dirs="\
  assets \
  images \
  images/basket \
  images/wallpost \
  images/picture \
  images/workgroup \
  data\
  data/attach \
  data/mailattach \
  data/mailattach/tmp \
  data/pass \
  data/uploads \
  data/visite \
  cache \
  cache/searchindex \
  var \
  var/cache \
  var/cache/dev \
  var/cache/test \
  var/cache/nginx/client_temp \
  var/log \
  tmp \
"

echo "Creating directories"

exec-in-container-asroot app \
  "mkdir --parents $dirs && chmod 777 $dirs && chown --recursive $CURRENT_USER $dirs"

echo "Done"
