#!/bin/bash

export FS_ENV=dev
export CURRENT_USER=$(id -u):$(id -g)

set -e

dir=$(dirname "$0")

# shellcheck source=./inc.sh
source "$dir"/inc.sh

PARAMS=( "$@" );
dc exec -T --user 33:33 app sh -c "HOME=./ php -f run.php" "${PARAMS[@]}"
