#!/bin/bash

export FS_ENV=dev
export CURRENT_USER=$(id -u):$(id -g)

# set -o errexit tells the shell to exit as soon as a command exits with non-zero status, i.e. fails
set -o errexit

dir=$(dirname "$0")
# source runs the content of the argument as if it was here (without launching a subshell!)
# shellcheck source=./__helping-functions.sh
source "$dir"/__helping-functions.sh

log-header "Calculating stats"
exec-in-container app bin/console foodsharing:daily-cronjob
exec-in-container app bin/console foodsharing:stats

log-header "All done"
