#!/usr/bin/env bash

export FS_ENV=test

dir=$(dirname "$0")

# shellcheck source=./__common.sh
source "$dir"/__common.sh

log-header "Running client js tests"
run-in-container client 'yarn && yarn lint && yarn test'
