#!/bin/bash
dir=$(dirname "$0")

# shellcheck source=./__helping-functions.sh
source "$dir"/__helping-functions.sh

# ENVS
export FS_ENV=test
export CURRENT_USER=$(id -u):$(id -g)

# set -o errexit tells the shell to exit as soon as a command exits with non-zero status, i.e. fails
set -o errexit

log-header "Running client js tests"
run-in-container client 'yarn && yarn lint && yarn test'
