#!/usr/bin/env bash

set -o errexit

dir=$(dirname "$0")
root="$dir/../.."
# shellcheck source=./__common.sh
source "$dir"/../__common.sh

log-header "Load API documentation"
"$root"/bin/console nelmio:apidoc:dump --format=json > "$root"/docs/data/api_dump.json

log-header "Build documentation"
cd "$root"/docs
yarn && yarn api:rebuild

echo
echo "GENERATION COMPLETE"
